In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/omarmendoza564/datos/main/datos/titanic.csv')
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### 1. Si la edad es null (na) llenar el campo con la media de la edad (usar el metodo fillna())

In [23]:
# Cambiar NaN por un valor
df['age'] = round(df.age.fillna(df.age.mean()), 1)
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,29.9,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### 2. Si embarqued es na llenar con S

In [24]:
df['embarked'] = df.embarked.fillna('S')
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,29.9,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN,NaN

##### 3. Cambiar los valores alfanumericos de sex a numero usando { 'female': 1, 'male': 0 }

In [25]:
df['sex'] = df['sex'].replace({"female": 1, "male": 0})
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",1.0,29.0,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",0.0,0.9,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",1.0,2.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",0.0,30.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,25.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",1.0,29.9,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",0.0,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",0.0,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",0.0,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN,NaN

##### 4. Cambiar los valores alfanumericos de embarked a numero usando { 'S': 0, 'C': 1, 'Q': 2 }

In [26]:
df['embarked'] = df['embarked'].replace({"S": 0, "C": 1, "Q": 2})
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",1.0,29.0,0.0,0.0,24160,211.3375,B5,0,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",0.0,0.9,1.0,2.0,113781,151.5500,C22 C26,0,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",1.0,2.0,1.0,2.0,113781,151.5500,C22 C26,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",0.0,30.0,1.0,2.0,113781,151.5500,C22 C26,0,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,25.0,1.0,2.0,113781,151.5500,C22 C26,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",1.0,29.9,1.0,0.0,2665,14.4542,NaN,1,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",0.0,26.5,0.0,0.0,2656,7.2250,NaN,1,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",0.0,27.0,0.0,0.0,2670,7.2250,NaN,1,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",0.0,29.0,0.0,0.0,315082,7.8750,NaN,0,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

##### 5. Crear una nueva variable llamada child con valor 1 para los pasajeros con una edad menor a 16 aÃ±os y 0 si el pasajero tiene 16 aÃ±os o mas

In [27]:
df_m16 = df['age'] < 16
df_m16

0       False
1        True
2        True
3       False
4       False
        ...
1305    False
1306    False
1307    False
1308    False
1309    False
Name: age, Length: 1310, dtype: bool

In [28]:
df[df_m16].sort_values(by='age', ascending=False)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
792,3.0,0.0,"Elias, Mr. Tannous",0.0,15.0,1.0,1.0,2695,7.2292,NaN,1,NaN,NaN,Syria
1300,3.0,1.0,"Yasbeck, Mrs. Antoni (Selini Alexander)",1.0,15.0,1.0,0.0,2659,14.4542,NaN,1,NaN,NaN,NaN
1007,3.0,1.0,"McGowan, Miss. Anna ""Annie""",1.0,15.0,0.0,0.0,330923,8.0292,NaN,2,NaN,NaN,NaN
1047,3.0,1.0,"Najib, Miss. Adele Kiamie ""Jane""",1.0,15.0,0.0,0.0,2667,7.2250,NaN,1,C,NaN,NaN
193,1.0,1.0,"Madill, Miss. Georgette Alexandra",1.0,15.0,0.0,1.0,24160,211.3375,B5,0,2,NaN,"St Louis, MO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,3.0,1.0,"Aks, Master. Philip Frank",0.0,0.8,0.0,1.0,392091,9.3500,NaN,0,11,NaN,"London, England Norfolk, VA"
427,2.0,1.0,"Hamalainen, Master. Viljo",0.0,0.7,1.0,1.0,250649,14.5000,NaN,0,4,NaN,"Detroit, MI"
1240,3.0,1.0,"Thomas, Master. Assad Alexander",0.0,0.4,0.0,1.0,2625,8.5167,NaN,1,16,NaN,NaN
747,3.0,0.0,"Danbom, Master. Gilbert Sigvard Emanuel",0.0,0.3,0.0,2.0,347080,14.4000,NaN,0,NaN,NaN,"Stanton, IA"
763,3.0,1.0,"Dean, Miss. Elizabeth Gladys ""Millvina""",1.0,0.2,1.0,2.0,C.A. 2315,20.5750,NaN,0,10,NaN,"Devon, England Wichita, KS"

##### 6. Eliminar las columnas ticket, cabin y name

In [29]:
columnas_a_eliminar = ['ticket', 'cabin', 'name']
df.drop(columnas_a_eliminar, axis=1, inplace=True)
df

,pclass,survived,sex,age,sibsp,parch,fare,embarked,boat,body,home.dest
0,1.0,1.0,1.0,29.0,0.0,0.0,211.3375,0,2,NaN,"St Louis, MO"
1,1.0,1.0,0.0,0.9,1.0,2.0,151.5500,0,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,1.0,2.0,1.0,2.0,151.5500,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,0.0,30.0,1.0,2.0,151.5500,0,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,1.0,25.0,1.0,2.0,151.5500,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,1.0,29.9,1.0,0.0,14.4542,1,NaN,NaN,NaN
1306,3.0,0.0,0.0,26.5,0.0,0.0,7.2250,1,NaN,304.0,NaN
1307,3.0,0.0,0.0,27.0,0.0,0.0,7.2250,1,NaN,NaN,NaN
1308,3.0,0.0,0.0,29.0,0.0,0.0,7.8750,0,NaN,NaN,NaN
1309,NaN,NaN,NaN,29.9,NaN,NaN,NaN,0,NaN,NaN,NaN

##### 7. Validar que no existan registros duplicados

In [30]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1305     True
1306    False
1307    False
1308    False
1309    False
Length: 1310, dtype: bool

##### 8. Listar los valores unicos del campo sex

In [31]:
df['sex'].unique

<bound method Series.unique of 0       1.0
1       0.0
2       1.0
3       0.0
4       1.0
       ...
1305    1.0
1306    0.0
1307    0.0
1308    0.0
1309    NaN
Name: sex, Length: 1310, dtype: float64>

##### 9. Quitar los espacios vacios de los campos que no sean numericos

In [32]:
df['home.dest'] = df['home.dest'].str.strip()
df

,pclass,survived,sex,age,sibsp,parch,fare,embarked,boat,body,home.dest
0,1.0,1.0,1.0,29.0,0.0,0.0,211.3375,0,2,NaN,"St Louis, MO"
1,1.0,1.0,0.0,0.9,1.0,2.0,151.5500,0,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,1.0,2.0,1.0,2.0,151.5500,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,0.0,30.0,1.0,2.0,151.5500,0,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,1.0,25.0,1.0,2.0,151.5500,0,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,1.0,29.9,1.0,0.0,14.4542,1,NaN,NaN,NaN
1306,3.0,0.0,0.0,26.5,0.0,0.0,7.2250,1,NaN,304.0,NaN
1307,3.0,0.0,0.0,27.0,0.0,0.0,7.2250,1,NaN,NaN,NaN
1308,3.0,0.0,0.0,29.0,0.0,0.0,7.8750,0,NaN,NaN,NaN
1309,NaN,NaN,NaN,29.9,NaN,NaN,NaN,0,NaN,NaN,NaN

##### 10.Guardar los datos limpios en un archivos json orientado a registros llamado iniciales_titanic_clean.json (sus iniciales)

In [36]:
df.to_json('AUNL_titanic_clean.json',
            orient="records",
            indent=2)
! type AUNL_titanic_clean.json

[
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":29.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":211.3375,
    "embarked":0,
    "boat":"2",
    "body":null,
    "home.dest":"St Louis, MO"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":0.9,
    "sibsp":1.0,
    "parch":2.0,
    "fare":151.55,
    "embarked":0,
    "boat":"11",
    "body":null,
    "home.dest":"Montreal, PQ \/ Chesterville, ON"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":1.0,
    "age":2.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":151.55,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Montreal, PQ \/ Chesterville, ON"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":30.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":151.55,
    "embarked":0,
    "boat":null,
    "body":135.0,
    "home.dest":"Montreal, PQ \/ Chesterville, ON"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":1.0,
    "age":25.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":151.55,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Montreal, PQ \/ Chesterville, ON"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":48.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":"3",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":63.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":77.9583,
    "embarked":0,
    "boat":"10",
    "body":null,
    "home.dest":"Hudson, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":39.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":0.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Belfast, NI"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":53.0,
    "sibsp":2.0,
    "parch":0.0,
    "fare":51.4792,
    "embarked":0,
    "boat":"D",
    "body":null,
    "home.dest":"Bayside, Queens, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":71.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":49.5042,
    "embarked":1,
    "boat":null,
    "body":22.0,
    "home.dest":"Montevideo, Uruguay"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":47.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":227.525,
    "embarked":1,
    "boat":null,
    "body":124.0,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":18.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":227.525,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":24.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":69.3,
    "embarked":1,
    "boat":"9",
    "body":null,
    "home.dest":"Paris, France"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":26.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":78.85,
    "embarked":0,
    "boat":"6",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":80.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":30.0,
    "embarked":0,
    "boat":"B",
    "body":null,
    "home.dest":"Hessle, Yorks"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":25.925,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":24.0,
    "sibsp":0.0,
    "parch":1.0,
    "fare":247.5208,
    "embarked":1,
    "boat":null,
    "body":null,
    "home.dest":"Montreal, PQ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":50.0,
    "sibsp":0.0,
    "parch":1.0,
    "fare":247.5208,
    "embarked":1,
    "boat":"6",
    "body":null,
    "home.dest":"Montreal, PQ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":32.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":76.2917,
    "embarked":1,
    "boat":"8",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":36.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":75.2417,
    "embarked":1,
    "boat":"A",
    "body":null,
    "home.dest":"Winnipeg, MN"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":37.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":52.5542,
    "embarked":0,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":47.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":52.5542,
    "embarked":0,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":26.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":30.0,
    "embarked":1,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":42.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":227.525,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":29.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":221.7792,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":25.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.0,
    "embarked":1,
    "boat":null,
    "body":148.0,
    "home.dest":"San Francisco, CA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":25.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":91.0792,
    "embarked":1,
    "boat":"7",
    "body":null,
    "home.dest":"Dowagiac, MI"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":19.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":91.0792,
    "embarked":1,
    "boat":"7",
    "body":null,
    "home.dest":"Dowagiac, MI"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":35.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":135.6333,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":28.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":"D",
    "body":null,
    "home.dest":"Stockholm, Sweden \/ Washington, DC"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":45.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":35.5,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Trenton, NJ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":40.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":31.0,
    "embarked":1,
    "boat":"7",
    "body":null,
    "home.dest":"Glen Ridge, NJ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":30.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":164.8667,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":"Youngstown, OH"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":58.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":"Birkdale, England Cleveland, Ohio"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":42.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"London \/ Winnipeg, MB"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":45.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":262.375,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":"Cooperstown, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":22.0,
    "sibsp":0.0,
    "parch":1.0,
    "fare":55.0,
    "embarked":0,
    "boat":"6",
    "body":null,
    "home.dest":"St Leonards-on-Sea, England Ohio"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":"9",
    "body":null,
    "home.dest":"Los Angeles, CA"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":41.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":30.5,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Pomeroy, WA"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":48.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":50.4958,
    "embarked":1,
    "boat":null,
    "body":208.0,
    "home.dest":"Omaha, NE"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":39.6,
    "embarked":1,
    "boat":null,
    "body":null,
    "home.dest":"Philadelphia, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":44.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":27.7208,
    "embarked":1,
    "boat":"6",
    "body":null,
    "home.dest":"Denver, CO"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":59.0,
    "sibsp":2.0,
    "parch":0.0,
    "fare":51.4792,
    "embarked":0,
    "boat":"D",
    "body":null,
    "home.dest":"Belmont, MA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":60.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":76.2917,
    "embarked":1,
    "boat":"8",
    "body":null,
    "home.dest":"Philadelphia, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":41.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":134.5,
    "embarked":1,
    "boat":"3",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":45.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Washington, DC"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":31.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":42.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.2875,
    "embarked":0,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":53.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":27.4458,
    "embarked":1,
    "boat":"6",
    "body":null,
    "home.dest":"Washington, DC"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":36.0,
    "sibsp":0.0,
    "parch":1.0,
    "fare":512.3292,
    "embarked":1,
    "boat":"3",
    "body":null,
    "home.dest":"Austria-Hungary \/ Germantown, Philadelphia, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":58.0,
    "sibsp":0.0,
    "parch":1.0,
    "fare":512.3292,
    "embarked":1,
    "boat":"3",
    "body":null,
    "home.dest":"Germantown, Philadelphia, PA"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":33.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":5.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":28.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":47.1,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Montevideo, Uruguay"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":17.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":47.1,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Montevideo, Uruguay"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":11.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":120.0,
    "embarked":0,
    "boat":"4",
    "body":null,
    "home.dest":"Bryn Mawr, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":14.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":120.0,
    "embarked":0,
    "boat":"4",
    "body":null,
    "home.dest":"Bryn Mawr, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":36.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":120.0,
    "embarked":0,
    "boat":"C",
    "body":null,
    "home.dest":"Bryn Mawr, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":36.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":120.0,
    "embarked":0,
    "boat":"4",
    "body":null,
    "home.dest":"Bryn Mawr, PA"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":49.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Ascot, Berkshire \/ Rochester, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":27.7208,
    "embarked":1,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":36.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":78.85,
    "embarked":0,
    "boat":null,
    "body":172.0,
    "home.dest":"Little Onn Hall, Staffs"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":76.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":78.85,
    "embarked":0,
    "boat":"6",
    "body":null,
    "home.dest":"Little Onn Hall, Staffs"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":46.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":61.175,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Amenia, ND"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":47.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":61.175,
    "embarked":0,
    "boat":"4",
    "body":null,
    "home.dest":"Amenia, ND"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":27.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":53.1,
    "embarked":0,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY \/ Ithaca, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":33.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":53.1,
    "embarked":0,
    "boat":"5",
    "body":null,
    "home.dest":"New York, NY \/ Ithaca, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":36.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":262.375,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":30.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":86.5,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":"London, England"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":45.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":29.7,
    "embarked":1,
    "boat":"7",
    "body":null,
    "home.dest":"Paris, France"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":1.0,
    "fare":55.0,
    "embarked":0,
    "boat":"6",
    "body":null,
    "home.dest":"St Leonards-on-Sea, England Ohio"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":0.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Liverpool, England \/ Belfast"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":27.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":136.7792,
    "embarked":1,
    "boat":null,
    "body":null,
    "home.dest":"Los Angeles, CA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":26.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":136.7792,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":"Los Angeles, CA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":22.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":151.55,
    "embarked":0,
    "boat":"11",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":52.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Stoughton, MA"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":47.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":25.5875,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Victoria, BC"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":39.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":83.1583,
    "embarked":1,
    "boat":"14",
    "body":null,
    "home.dest":"Lakewood, NJ"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":37.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":83.1583,
    "embarked":1,
    "boat":null,
    "body":null,
    "home.dest":"Lakewood, NJ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":64.0,
    "sibsp":0.0,
    "parch":2.0,
    "fare":83.1583,
    "embarked":1,
    "boat":"14",
    "body":null,
    "home.dest":"Lakewood, NJ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":55.0,
    "sibsp":2.0,
    "parch":0.0,
    "fare":25.7,
    "embarked":0,
    "boat":"2",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":29.9,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Roachdale, IN"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":70.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":71.0,
    "embarked":0,
    "boat":null,
    "body":269.0,
    "home.dest":"Milwaukee, WI"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":36.0,
    "sibsp":0.0,
    "parch":2.0,
    "fare":71.0,
    "embarked":0,
    "boat":"7",
    "body":null,
    "home.dest":"Milwaukee, WI"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":64.0,
    "sibsp":1.0,
    "parch":1.0,
    "fare":26.55,
    "embarked":0,
    "boat":"7",
    "body":null,
    "home.dest":"Milwaukee, WI"
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":39.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":71.2833,
    "embarked":1,
    "boat":null,
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":38.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":71.2833,
    "embarked":1,
    "boat":"4",
    "body":null,
    "home.dest":"New York, NY"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":51.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":26.55,
    "embarked":0,
    "boat":"5 9",
    "body":null,
    "home.dest":"Lima, Peru"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":27.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":30.5,
    "embarked":0,
    "boat":"3",
    "body":null,
    "home.dest":"Philadelphia, PA"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":33.0,
    "sibsp":0.0,
    "parch":0.0,
    "fare":151.55,
    "embarked":0,
    "boat":"8",
    "body":null,
    "home.dest":null
  },
  {
    "pclass":1.0,
    "survived":0.0,
    "sex":0.0,
    "age":31.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":52.0,
    "embarked":0,
    "boat":null,
    "body":null,
    "home.dest":"Montreal, PQ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":27.0,
    "sibsp":1.0,
    "parch":2.0,
    "fare":52.0,
    "embarked":0,
    "boat":"3",
    "body":null,
    "home.dest":"Montreal, PQ"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":0.0,
    "age":31.0,
    "sibsp":1.0,
    "parch":0.0,
    "fare":57.0,
    "embarked":0,
    "boat":"3",
    "body":null,
    "home.dest":"Calgary, AB"
  },
  {
    "pclass":1.0,
    "survived":1.0,
    "sex":1.0,
    "age":17.0,
    "sibsp":1.0,
    "parch":0.0,